<script>
  import { createEventDispatcher, onMount } from 'svelte'
  import jsPDF from 'jspdf'
  
  const dispatch = createEventDispatcher()
  
  export let selectedPatient
  export let illnesses
  export let prescriptions
  export let symptoms
  
  let loading = false
  
  // Generate PDF prescription
  const generatePDF = async () => {
    loading = true
    
    try {
      const doc = new jsPDF()
      const currentDate = new Date().toLocaleDateString()
      
      // Header
      doc.setFontSize(20)
      doc.text('PRESCRIPTION', 20, 30)
      
      // Doctor info
      doc.setFontSize(12)
      doc.text('Dr. [Doctor Name]', 20, 50)
      doc.text('Medical License: [License Number]', 20, 60)
      doc.text(`Date: ${currentDate}`, 20, 70)
      
      // Patient info
      doc.text('Patient Information:', 20, 90)
      doc.text(`Name: ${selectedPatient.firstName} ${selectedPatient.lastName}`, 20, 100)
      doc.text(`ID: ${selectedPatient.idNumber}`, 20, 110)
      doc.text(`DOB: ${selectedPatient.dateOfBirth}`, 20, 120)
      
      // Current Illnesses
      if (illnesses.length > 0) {
        doc.text('Current Illnesses:', 20, 140)
        let yPos = 150
        illnesses.forEach((illness, index) => {
          if (yPos > 250) {
            doc.addPage()
            yPos = 20
          }
          doc.text(`${index + 1}. ${illness.name} (${illness.status})`, 25, yPos)
          if (illness.description) {
            doc.text(`   ${illness.description}`, 25, yPos + 10)
            yPos += 20
          } else {
            yPos += 15
          }
        })
      }
      
      // Current Symptoms
      if (symptoms.length > 0) {
        doc.text('Current Symptoms:', 20, yPos + 10)
        yPos += 20
        symptoms.forEach((symptom, index) => {
          if (yPos > 250) {
            doc.addPage()
            yPos = 20
          }
          doc.text(`${index + 1}. ${symptom.description}`, 25, yPos)
          doc.text(`   Severity: ${symptom.severity}`, 25, yPos + 10)
          if (symptom.duration) {
            doc.text(`   Duration: ${symptom.duration}`, 25, yPos + 20)
            yPos += 30
          } else {
            yPos += 20
          }
        })
      }
      
      // Prescribed Prescriptions
      if (prescriptions.length > 0) {
        doc.text('Prescribed Prescriptions:', 20, yPos + 10)
        yPos += 20
        prescriptions.forEach((medication, index) => {
          if (yPos > 250) {
            doc.addPage()
            yPos = 20
          }
          doc.text(`${index + 1}. ${medication.name}`, 25, yPos)
          doc.text(`   Dosage: ${medication.dosage}`, 25, yPos + 10)
          doc.text(`   Frequency: ${medication.frequency}`, 25, yPos + 20)
          if (medication.instructions) {
            doc.text(`   Instructions: ${medication.instructions}`, 25, yPos + 30)
            yPos += 40
          } else {
            yPos += 30
          }
        })
      }
      
      // Footer
      const pageCount = doc.internal.getNumberOfPages()
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(10)
        doc.text(`Page ${i} of ${pageCount}`, 20, doc.internal.pageSize.height - 10)
        doc.text('Generated by Prescribe Patient Management System', 100, doc.internal.pageSize.height - 10)
      }
      
      // Generate filename with capital letter as per user preference
      const filename = `Prescription_${selectedPatient.firstName}_${selectedPatient.lastName}_${currentDate.replace(/\//g, '-')}.pdf`
      
      // Save the PDF
      doc.save(filename)
      
      console.log('PDF generated successfully')
      
    } catch (error) {
      console.error('Error generating PDF:', error)
    } finally {
      loading = false
    }
  }
  
  // Handle close
  const handleClose = () => {
    dispatch('close')
  }
</script>

<div class="modal show d-block" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          <i class="fas fa-file-pdf me-2"></i>Generate Prescription PDF
        </h5>
        <button 
          type="button" 
          class="btn-close" 
          on:click={handleClose}
          disabled={loading}
        ></button>
      </div>
      
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6">
            <h6>Patient Information</h6>
            <p><strong>Name:</strong> {selectedPatient.firstName} {selectedPatient.lastName}</p>
            <p><strong>ID:</strong> {selectedPatient.idNumber}</p>
            <p><strong>DOB:</strong> {selectedPatient.dateOfBirth}</p>
          </div>
          <div class="col-md-6">
            <h6>Summary</h6>
            <p><strong>Illnesses:</strong> {illnesses.length}</p>
            <p><strong>Prescriptions:</strong> {prescriptions.length}</p>
            <p><strong>Symptoms:</strong> {symptoms.length}</p>
          </div>
        </div>
        
        {#if illnesses.length > 0}
          <div class="mt-3">
            <h6>Current Illnesses</h6>
            <ul class="list-group list-group-flush">
              {#each illnesses as illness}
                <li class="list-group-item">
                  <strong>{illness.name}</strong> ({illness.status})
                  {#if illness.description}
                    <br><small class="text-muted">{illness.description}</small>
                  {/if}
                </li>
              {/each}
            </ul>
          </div>
        {/if}
        
        {#if prescriptions.length > 0}
          <div class="mt-3">
            <h6>Prescribed Prescriptions</h6>
            <ul class="list-group list-group-flush">
              {#each prescriptions as medication}
                <li class="list-group-item">
                  <strong>{medication.name}</strong> - {medication.dosage}
                  <br><small class="text-muted">{medication.frequency}</small>
                  {#if medication.instructions}
                    <br><small class="text-muted">Instructions: {medication.instructions}</small>
                  {/if}
                </li>
              {/each}
            </ul>
          </div>
        {/if}
        
        {#if symptoms.length > 0}
          <div class="mt-3">
            <h6>Current Symptoms</h6>
            <ul class="list-group list-group-flush">
              {#each symptoms as symptom}
                <li class="list-group-item">
                  <strong>{symptom.description}</strong> ({symptom.severity})
                  {#if symptom.duration}
                    <br><small class="text-muted">Duration: {symptom.duration}</small>
                  {/if}
                </li>
              {/each}
            </ul>
          </div>
        {/if}
      </div>
      
      <div class="modal-footer">
        <button 
          type="button" 
          class="btn btn-primary" 
          on:click={generatePDF}
          disabled={loading}
        >
          {#if loading}
            <span class="spinner-border spinner-border-sm me-2" role="status"></span>
          {/if}
          <i class="fas fa-download me-1"></i>Generate & Download PDF
        </button>
        <button 
          type="button" 
          class="btn btn-secondary" 
          on:click={handleClose}
          disabled={loading}
        >
          <i class="fas fa-times me-1"></i>Cancel
        </button>
      </div>
    </div>
  </div>
</div>

<div class="modal-backdrop show"></div>
