const currencyByCountry = {
  'Sri Lanka': 'LKR',
  'United States': 'USD',
  'United Kingdom': 'GBP',
  'Canada': 'CAD',
  'Australia': 'AUD',
  'New Zealand': 'NZD',
  'India': 'INR',
  'Pakistan': 'PKR',
  'Bangladesh': 'BDT',
  'Nepal': 'NPR',
  'Bhutan': 'BTN',
  'Myanmar': 'MMK',
  'Thailand': 'THB',
  'Vietnam': 'VND',
  'Malaysia': 'MYR',
  'Singapore': 'SGD',
  'Indonesia': 'IDR',
  'Philippines': 'PHP',
  'China': 'CNY',
  'Japan': 'JPY',
  'South Korea': 'KRW',
  'Hong Kong': 'HKD',
  'Taiwan': 'TWD',
  'United Arab Emirates': 'AED',
  'Saudi Arabia': 'SAR',
  'Qatar': 'QAR',
  'Kuwait': 'KWD',
  'Oman': 'OMR',
  'Bahrain': 'BHD',
  'Israel': 'ILS',
  'Turkey': 'TRY',
  'Russia': 'RUB',
  'Ukraine': 'UAH',
  'Switzerland': 'CHF',
  'Norway': 'NOK',
  'Sweden': 'SEK',
  'Denmark': 'DKK',
  'Poland': 'PLN',
  'Czech Republic': 'CZK',
  'Hungary': 'HUF',
  'Romania': 'RON',
  'Bulgaria': 'BGN',
  'Greece': 'EUR',
  'Germany': 'EUR',
  'France': 'EUR',
  'Italy': 'EUR',
  'Spain': 'EUR',
  'Portugal': 'EUR',
  'Netherlands': 'EUR',
  'Belgium': 'EUR',
  'Austria': 'EUR',
  'Ireland': 'EUR',
  'Finland': 'EUR',
  'Luxembourg': 'EUR',
  'South Africa': 'ZAR',
  'Kenya': 'KES',
  'Nigeria': 'NGN',
  'Ghana': 'GHS',
  'Egypt': 'EGP',
  'Morocco': 'MAD',
  'Tunisia': 'TND',
  'Algeria': 'DZD',
  'Ethiopia': 'ETB',
  'Brazil': 'BRL',
  'Argentina': 'ARS',
  'Chile': 'CLP',
  'Colombia': 'COP',
  'Peru': 'PEN',
  'Mexico': 'MXN'
}

export const resolveCurrencyFromCountry = (country) => {
  const name = String(country || '').trim()
  if (!name) return ''
  return currencyByCountry[name] || 'USD'
}

export const getCurrencyByCountry = () => ({ ...currencyByCountry })
