import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

describe('PatientDetails import regression', () => {
  it('keeps chargeCalculationService imported when medication quantity logic uses it', () => {
    const __filename = fileURLToPath(import.meta.url)
    const __dirname = path.dirname(__filename)
    const patientDetailsPath = path.resolve(__dirname, '../../components/PatientDetails.svelte')
    const source = fs.readFileSync(patientDetailsPath, 'utf8')

    expect(source).toContain("import chargeCalculationService from '../services/pharmacist/chargeCalculationService.js'")
    expect(source).toContain('chargeCalculationService.parseMedicationQuantity')
  })

  it('keeps camera report OCR flow wired in report form', () => {
    const __filename = fileURLToPath(import.meta.url)
    const __dirname = path.dirname(__filename)
    const patientDetailsPath = path.resolve(__dirname, '../../components/PatientDetails.svelte')
    const source = fs.readFileSync(patientDetailsPath, 'utf8')

    expect(source).toContain("let reportType = 'camera'")
    expect(source).toContain("id=\"report-camera\"")
    expect(source).toContain('startCameraScan')
    expect(source).toContain('captureCameraPhoto')
    expect(source).toContain('runCameraOcr')
    expect(source).toContain("let cameraSource = 'mobile'")
    expect(source).toContain('Mobile Phone')
    expect(source).toContain('Laptop Camera')
    expect(source).toContain('mobileCameraQrUrl')
    expect(source).toContain('mobileCameraAccessCode')
    expect(source).toContain('generateMobileAccessCode')
    expect(source).toContain("nextUrl.searchParams.set('mobile-capture', '1')")
    expect(source).toContain("nextUrl.searchParams.set('code', mobileCameraAccessCode)")
    expect(source).toContain('Scan the QR code using your phone camera.')
    expect(source).not.toContain('Security code:')
    expect(source).not.toContain('Upload photo captured from mobile')
    expect(source).toContain('Mobile camera QR code')
    expect(source).toContain('cameraOcrProgress')
    expect(source).toContain('cameraOcrProgressLabel')
    expect(source).toContain('OCR progress bar')
    expect(source).toContain('Extracting... {cameraOcrProgress}%')
    expect(source).toContain("cameraOcrLoading || (reportText && reportText.trim())")
    expect(source).toContain('Extract Text')
    expect(source).not.toContain('Extract Text (OpenAI OCR)')
    expect(source).toContain('grid grid-cols-1 lg:grid-cols-2 gap-3')
    expect(source).toContain('Captured Photo')
    expect(source).toContain('detectPreviewCorners')
    expect(source).toContain('reportDetectedCorners')
    expect(source).toContain('reportSelectedAreaDataUrl')
    expect(source).toContain('createSelectedAreaDataUrl')
    expect(source).toContain("if (reportType === 'camera' && effectiveReportType === 'image')")
    expect(source).toContain("reportError = 'Please select a valid area before saving.'")
    expect(source).toContain("name: 'camera-selected-area.png'")
    expect(source).not.toContain("name: 'camera-capture.jpg'")
    expect(source).toContain('const shouldShowSelectedAreaPreview = (report) => {')
    expect(source).toContain('selected !== primary')
    expect(source).toContain('{#if shouldShowSelectedAreaPreview(report)}')
    expect(source).toContain('{#if shouldShowSelectedAreaPreview(viewingReport)}')
    expect(source).toContain("let savingReport = false")
    expect(source).toContain("if (savingReport) return")
    expect(source).toContain("disabled={savingReport}")
    expect(source).toContain("Saving...")
    expect(source).toContain("let savingReportProgress = 0")
    expect(source).toContain("let savingReportProgressLabel = ''")
    expect(source).toContain("let savingReportProgressTimer = null")
    expect(source).toContain("savingReportProgressLabel = reportType === 'camera' ? 'Uploading selected area...' : 'Uploading report...'")
    expect(source).toContain('Report save progress bar')
    expect(source).toContain("style={`width: ${savingReportProgress}%`}")
    expect(source).toContain("if (savingReportProgressTimer)")
    expect(source).toContain('selectedAreaDataUrl: effectiveReportType === \'image\'')
    expect(source).toContain('startCornerDrag')
    expect(source).toContain('updateDraggedCorner')
    expect(source).toContain('on:pointerdown={(event) => startCornerDrag(index, event)}')
    expect(source).toContain('openaiService.extractTextFromImage')
    expect(source).toContain("type: 'reportImageOcr'")
    expect(source).toContain("import { isUnreadableText } from '../utils/unreadableText.js'")
    expect(source).toContain('if (isUnreadableText(extractedText))')
    expect(source).toContain("cameraOcrError = 'Extracted text is unreadable. Please retake a clearer photo and try again.'")
    expect(source).toContain("reportText = ''")
    expect(source).toContain("cameraOcrLoading || (reportText && reportText.trim())")
    expect(source).not.toContain('Camera Capture</label>')
    expect(source).not.toContain('Extracted Text (Editable)')
    expect(source).not.toContain('Detect 4 Corners')
    expect(source).not.toContain('Extracted text will appear here after OCR is generated.')
    expect(source).not.toContain('Report Form Scanner')
    expect(source).not.toContain('Scan / Choose Pages')
    expect(source).toContain("mobileCaptureSessionStatus === 'photo_ready' ? 'Photo received. Processing...' : 'Waiting for photo upload...'")
    expect(source).toContain('cameraOcrProgress}%')
    expect(source).toContain('style={`width: ${cameraOcrProgress}%`}')
    expect(source).toContain('firebaseStorage.subscribeMobileCaptureSession')
    expect(source).toContain('mobileCaptureSessionUnsubscribe')
    expect(source).toContain("mobileCaptureSessionStatus === 'opened'")
    expect(source).toContain("status: 'consumed'")
  })

  it('keeps AI Analysis under Diagnoses instead of as a dedicated workflow tab', () => {
    const __filename = fileURLToPath(import.meta.url)
    const __dirname = path.dirname(__filename)
    const patientDetailsPath = path.resolve(__dirname, '../../components/PatientDetails.svelte')
    const source = fs.readFileSync(patientDetailsPath, 'utf8')

    expect(source).toContain("const allTabs = ['overview', 'symptoms', 'reports', 'diagnoses', 'prescriptions']")
    expect(source).toContain("const tabOrder = ['overview', 'symptoms', 'reports', 'diagnoses', 'prescriptions']")
    expect(source).not.toContain("{#if activeTab === 'ai-analysis'}")
    expect(source).toContain('showAiAnalysisUnderDiagnoses')
    expect(source).toContain('Hide AI Analysis')
    expect(source).toContain("title=\"Continue to Prescriptions tab\"")
  })
})
